I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script_opening.rpy", line 78, in script
    show kog shirt_right_color at center
Exception: Image 'kog' does not accept attributes 'shirt_right_color'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script_opening.rpy", line 78, in script
    show kog shirt_right_color at center
  File "renpy/ast.py", line 1197, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "renpy/ast.py", line 1167, in show_imspec
    atl=atl)
  File "renpy/exports.py", line 742, in show
    if not base.find_target() and renpy.config.missing_show:
  File "renpy/display/image.py", line 409, in find_target
    self.target = target._duplicate(a)
  File "renpy/display/layout.py", line 153, in _duplicate
    args.extraneous()
  File "renpy/display/core.py", line 271, in extraneous
    " ".join(self.args),
Exception: Image 'kog' does not accept attributes 'shirt_right_color'.

Windows-10-10.0.22621
Ren'Py 7.4.11.2266
Shoot Tomorrow 1.0
Thu Jun 20 17:22:30 2024
