I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script_test.rpy", line 24, in script
    jump round2R
ScriptError: could not find label 'round2R'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script_test.rpy", line 24, in script
    jump round2R
  File "renpy/ast.py", line 1757, in execute
    rv = renpy.game.script.lookup(target)
  File "renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'round2R'.

Windows-10-10.0.22621
Ren'Py 7.4.11.2266
Shoot Tomorrow 1.0
Fri Jun 21 17:20:34 2024
